import { EssentialCharacteristic } from "@/models/product/characteristic";
import { MadData } from "@/models/product/deliverydata";
import { Flyer } from "@/models/product/flyer";
import { Price } from "@/models/product/price";
import { PriorityPushOp } from "@/models/product/pushop";
import { ImageProduct } from "@/models/product/imageproduct";

export interface Product {
  pk: string;
  code: string;
  name: string;
  offerCode: string | null;
  estAffichable: boolean;
  paymentFullCB: number;
  isMp: boolean;
  breadcrumbStructure: string[];
  univers: string;
  marche: string;
  segment: string;
  brand: string | null;
  family: number;
  role: string;
  variantLabel: string;
  productNote: string;
  numberOfReview: number;
  offerState: string | null;
  offerGrade: string | null;
  offers: any | null;
  offer: any | null;
  deliveryStatus: string | null;
  calculatedName: string | null;
  availability: string;
  numberOfStoresHavingStock: number;
  offerNumber: number;
  addToCartDirect: boolean;
  pushOpStock: string | null;
  price: Price;
  vendor: string | null;
  retraitMadsData: MadData[];
  deliveryMadData: MadData;
  fastDeliveryMadData: MadData | null;
  priorityPushOp: PriorityPushOp;
  refFournisseur: string;
  flyers: Flyer[];
  offerToShow: string | null;
  promoCode: string;
  nameNormalized: string;
  calculatedLabelNormalized: string;
  urlPicture: string;
  urlProduct: string;
  primaryImages: { [key: string]: ImageProduct };
  ambianceImages: { [key: string]: ImageProduct };
  essentialCharacteristics: EssentialCharacteristic[];
  repairabilityIndex: string | null;
  energyClassData: any | null;
}